export const NOTES_REGISTER_REQUEST = "NOTES_REGISTER";
export const NOTES_REGISTER_SUCCESS = "NOTES_SUCCESS";
export const NOTES_REGISTER_FAIL = "NOTES_REGISTER_FAIL";

export const NOTES_CREATE_REQUEST = "NOTES_CREATE_REQUEST";
export const NOTES_CREATE_SUCCESS = "NOTES_CREATE_SUCCESS";
export const NOTES_CREATE_FAIL = "NOTES_CREATE_FAIL";